# Generated by Django 3.1.2 on 2020-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands', models.TextField()),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('storeName', models.TextField()),
                ('count', models.IntegerField()),
                ('pic', models.TextField()),
            ],
        ),
    ]
