# Generated by Django 3.1.2 on 2020-10-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20201022_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.store')),
            ],
        ),
    ]
